name: 'Ctrain68'
description: 'Git Diff for mono repo'
author: 'Goodna Gang'
outputs:
  to_build:
    description: 'json object of which apps to build'
runs:
  using: 'node16'
  main: 'dist/index.js'
